/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * DeviceGroupModel
 */

public class DeviceGroupModel {
  @SerializedName("creationTime")
  private Long creationTime = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("deviceCount")
  private Long deviceCount = null;

  @SerializedName("groupId")
  private String groupId = null;

  @SerializedName("lastUpdateTime")
  private Long lastUpdateTime = null;

  public DeviceGroupModel creationTime(Long creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty(value = "")
  public Long getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Long creationTime) {
    this.creationTime = creationTime;
  }

  public DeviceGroupModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DeviceGroupModel deviceCount(Long deviceCount) {
    this.deviceCount = deviceCount;
    return this;
  }

   /**
   * Get deviceCount
   * @return deviceCount
  **/
  @ApiModelProperty(value = "")
  public Long getDeviceCount() {
    return deviceCount;
  }

  public void setDeviceCount(Long deviceCount) {
    this.deviceCount = deviceCount;
  }

  public DeviceGroupModel groupId(String groupId) {
    this.groupId = groupId;
    return this;
  }

   /**
   * Get groupId
   * @return groupId
  **/
  @ApiModelProperty(value = "")
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(String groupId) {
    this.groupId = groupId;
  }

  public DeviceGroupModel lastUpdateTime(Long lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
    return this;
  }

   /**
   * Get lastUpdateTime
   * @return lastUpdateTime
  **/
  @ApiModelProperty(value = "")
  public Long getLastUpdateTime() {
    return lastUpdateTime;
  }

  public void setLastUpdateTime(Long lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceGroupModel deviceGroupModel = (DeviceGroupModel) o;
    return Objects.equals(this.creationTime, deviceGroupModel.creationTime) &&
        Objects.equals(this.description, deviceGroupModel.description) &&
        Objects.equals(this.deviceCount, deviceGroupModel.deviceCount) &&
        Objects.equals(this.groupId, deviceGroupModel.groupId) &&
        Objects.equals(this.lastUpdateTime, deviceGroupModel.lastUpdateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationTime, description, deviceCount, groupId, lastUpdateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceGroupModel {\n");
    
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    deviceCount: ").append(toIndentedString(deviceCount)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

