/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Device model
 */
@ApiModel(description = "Device model")

public class DeviceModel {
  @SerializedName("accountID")
  private String accountID = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("uniqueId")
  private String uniqueId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("deviceCode")
  private String deviceCode = null;

  @SerializedName("deviceType")
  private String deviceType = null;

  @SerializedName("vehicleID")
  private String vehicleID = null;

  @SerializedName("vehicleMake")
  private String vehicleMake = null;

  @SerializedName("vehicleModel")
  private String vehicleModel = null;

  @SerializedName("licensePlate")
  private String licensePlate = null;

  @SerializedName("licenseExpiration")
  private Long licenseExpiration = null;

  @SerializedName("reminderInterval")
  private String reminderInterval = null;

  @SerializedName("reminderMessage")
  private String reminderMessage = null;

  @SerializedName("maintenanceNotes")
  private String maintenanceNotes = null;

  @SerializedName("maintenanceInterval1")
  private Double maintenanceInterval1 = null;

  @SerializedName("lastMaintenance1")
  private Double lastMaintenance1 = null;

  @SerializedName("maintenanceInterval2")
  private Double maintenanceInterval2 = null;

  @SerializedName("lastMaintenance2")
  private Double lastMaintenance2 = null;

  @SerializedName("faultCodes")
  private String faultCodes = null;

  @SerializedName("notifyEmail")
  private String notifyEmail = null;

  @SerializedName("equipmentType")
  private String equipmentType = null;

  @SerializedName("resetTime")
  private Long resetTime = null;

  @SerializedName("installTime")
  private Long installTime = null;

  @SerializedName("lastStopTime")
  private Long lastStopTime = null;

  @SerializedName("lastStartTime")
  private Long lastStartTime = null;

  @SerializedName("lastIgnitionOnTime")
  private Long lastIgnitionOnTime = null;

  @SerializedName("lastIgnitionOffTime")
  private Long lastIgnitionOffTime = null;

  @SerializedName("creationDate")
  private Long creationDate = null;

  @SerializedName("lastServiceTime")
  private Long lastServiceTime = null;

  @SerializedName("nextServiceTime")
  private Long nextServiceTime = null;

  @SerializedName("lastGPSTimestamp")
  private Long lastGPSTimestamp = null;

  @SerializedName("lastEventTimestamp")
  private Long lastEventTimestamp = null;

  @SerializedName("suspended")
  private Boolean suspended = null;

  @SerializedName("notifyEnable")
  private Boolean notifyEnable = null;

  @SerializedName("maximumSpeed")
  private Double maximumSpeed = null;

  @SerializedName("lastOdometerKM")
  private Double lastOdometerKM = null;

  @SerializedName("lastEngineHours")
  private Double lastEngineHours = null;

  @SerializedName("engineHoursOffset")
  private Double engineHoursOffset = null;

  @SerializedName("odometerOffsetKM")
  private Double odometerOffsetKM = null;

  @SerializedName("lastFuelLevel")
  private Double lastFuelLevel = null;

  @SerializedName("lastEngHoursMaint")
  private Double lastEngHoursMaint = null;

  @SerializedName("engHoursMaintInterval")
  private Double engHoursMaintInterval = null;

  @SerializedName("lastValidLatitude")
  private Double lastValidLatitude = null;

  @SerializedName("lastValidLongitude")
  private Double lastValidLongitude = null;

  @SerializedName("lastValidHeading")
  private Double lastValidHeading = null;

  @SerializedName("statusCode")
  private Integer statusCode = null;

  @SerializedName("statusCodeText")
  private String statusCodeText = null;

  @SerializedName("statusColor")
  private String statusColor = null;

  @SerializedName("ignition")
  private String ignition = null;

  @SerializedName("stopTime")
  private String stopTime = null;

  public DeviceModel accountID(String accountID) {
    this.accountID = accountID;
    return this;
  }

   /**
   * Account ID
   * @return accountID
  **/
  @ApiModelProperty(required = true, value = "Account ID")
  public String getAccountID() {
    return accountID;
  }

  public void setAccountID(String accountID) {
    this.accountID = accountID;
  }

  public DeviceModel deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Device ID
   * @return deviceId
  **/
  @ApiModelProperty(required = true, value = "Device ID")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public DeviceModel uniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

   /**
   * Unique ID
   * @return uniqueId
  **/
  @ApiModelProperty(value = "Unique ID")
  public String getUniqueId() {
    return uniqueId;
  }

  public void setUniqueId(String uniqueId) {
    this.uniqueId = uniqueId;
  }

  public DeviceModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Device Description
   * @return description
  **/
  @ApiModelProperty(value = "Device Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DeviceModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Display Name
   * @return displayName
  **/
  @ApiModelProperty(value = "Display Name")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public DeviceModel deviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
    return this;
  }

   /**
   * Device code
   * @return deviceCode
  **/
  @ApiModelProperty(value = "Device code")
  public String getDeviceCode() {
    return deviceCode;
  }

  public void setDeviceCode(String deviceCode) {
    this.deviceCode = deviceCode;
  }

  public DeviceModel deviceType(String deviceType) {
    this.deviceType = deviceType;
    return this;
  }

   /**
   * Device type
   * @return deviceType
  **/
  @ApiModelProperty(value = "Device type")
  public String getDeviceType() {
    return deviceType;
  }

  public void setDeviceType(String deviceType) {
    this.deviceType = deviceType;
  }

  public DeviceModel vehicleID(String vehicleID) {
    this.vehicleID = vehicleID;
    return this;
  }

   /**
   * VIN
   * @return vehicleID
  **/
  @ApiModelProperty(value = "VIN")
  public String getVehicleID() {
    return vehicleID;
  }

  public void setVehicleID(String vehicleID) {
    this.vehicleID = vehicleID;
  }

  public DeviceModel vehicleMake(String vehicleMake) {
    this.vehicleMake = vehicleMake;
    return this;
  }

   /**
   * Vehicle Make
   * @return vehicleMake
  **/
  @ApiModelProperty(value = "Vehicle Make")
  public String getVehicleMake() {
    return vehicleMake;
  }

  public void setVehicleMake(String vehicleMake) {
    this.vehicleMake = vehicleMake;
  }

  public DeviceModel vehicleModel(String vehicleModel) {
    this.vehicleModel = vehicleModel;
    return this;
  }

   /**
   * Vehicle Model
   * @return vehicleModel
  **/
  @ApiModelProperty(value = "Vehicle Model")
  public String getVehicleModel() {
    return vehicleModel;
  }

  public void setVehicleModel(String vehicleModel) {
    this.vehicleModel = vehicleModel;
  }

  public DeviceModel licensePlate(String licensePlate) {
    this.licensePlate = licensePlate;
    return this;
  }

   /**
   * Vehicle Plate
   * @return licensePlate
  **/
  @ApiModelProperty(value = "Vehicle Plate")
  public String getLicensePlate() {
    return licensePlate;
  }

  public void setLicensePlate(String licensePlate) {
    this.licensePlate = licensePlate;
  }

  public DeviceModel licenseExpiration(Long licenseExpiration) {
    this.licenseExpiration = licenseExpiration;
    return this;
  }

   /**
   * License Expiration UTC
   * @return licenseExpiration
  **/
  @ApiModelProperty(example = "1514707261000", value = "License Expiration UTC")
  public Long getLicenseExpiration() {
    return licenseExpiration;
  }

  public void setLicenseExpiration(Long licenseExpiration) {
    this.licenseExpiration = licenseExpiration;
  }

  public DeviceModel reminderInterval(String reminderInterval) {
    this.reminderInterval = reminderInterval;
    return this;
  }

   /**
   * Reminder Interval
   * @return reminderInterval
  **/
  @ApiModelProperty(value = "Reminder Interval")
  public String getReminderInterval() {
    return reminderInterval;
  }

  public void setReminderInterval(String reminderInterval) {
    this.reminderInterval = reminderInterval;
  }

  public DeviceModel reminderMessage(String reminderMessage) {
    this.reminderMessage = reminderMessage;
    return this;
  }

   /**
   * Reminder Message
   * @return reminderMessage
  **/
  @ApiModelProperty(value = "Reminder Message")
  public String getReminderMessage() {
    return reminderMessage;
  }

  public void setReminderMessage(String reminderMessage) {
    this.reminderMessage = reminderMessage;
  }

  public DeviceModel maintenanceNotes(String maintenanceNotes) {
    this.maintenanceNotes = maintenanceNotes;
    return this;
  }

   /**
   * Maintenance Notes
   * @return maintenanceNotes
  **/
  @ApiModelProperty(value = "Maintenance Notes")
  public String getMaintenanceNotes() {
    return maintenanceNotes;
  }

  public void setMaintenanceNotes(String maintenanceNotes) {
    this.maintenanceNotes = maintenanceNotes;
  }

  public DeviceModel maintenanceInterval1(Double maintenanceInterval1) {
    this.maintenanceInterval1 = maintenanceInterval1;
    return this;
  }

   /**
   * Maintenance Interval1
   * @return maintenanceInterval1
  **/
  @ApiModelProperty(value = "Maintenance Interval1")
  public Double getMaintenanceInterval1() {
    return maintenanceInterval1;
  }

  public void setMaintenanceInterval1(Double maintenanceInterval1) {
    this.maintenanceInterval1 = maintenanceInterval1;
  }

  public DeviceModel lastMaintenance1(Double lastMaintenance1) {
    this.lastMaintenance1 = lastMaintenance1;
    return this;
  }

   /**
   * Last Maintenance 1
   * @return lastMaintenance1
  **/
  @ApiModelProperty(value = "Last Maintenance 1")
  public Double getLastMaintenance1() {
    return lastMaintenance1;
  }

  public void setLastMaintenance1(Double lastMaintenance1) {
    this.lastMaintenance1 = lastMaintenance1;
  }

  public DeviceModel maintenanceInterval2(Double maintenanceInterval2) {
    this.maintenanceInterval2 = maintenanceInterval2;
    return this;
  }

   /**
   * Maintenance Interval2
   * @return maintenanceInterval2
  **/
  @ApiModelProperty(value = "Maintenance Interval2")
  public Double getMaintenanceInterval2() {
    return maintenanceInterval2;
  }

  public void setMaintenanceInterval2(Double maintenanceInterval2) {
    this.maintenanceInterval2 = maintenanceInterval2;
  }

  public DeviceModel lastMaintenance2(Double lastMaintenance2) {
    this.lastMaintenance2 = lastMaintenance2;
    return this;
  }

   /**
   * Last Maintenance 2
   * @return lastMaintenance2
  **/
  @ApiModelProperty(value = "Last Maintenance 2")
  public Double getLastMaintenance2() {
    return lastMaintenance2;
  }

  public void setLastMaintenance2(Double lastMaintenance2) {
    this.lastMaintenance2 = lastMaintenance2;
  }

  public DeviceModel faultCodes(String faultCodes) {
    this.faultCodes = faultCodes;
    return this;
  }

   /**
   * Last Fault Code
   * @return faultCodes
  **/
  @ApiModelProperty(value = "Last Fault Code")
  public String getFaultCodes() {
    return faultCodes;
  }

  public void setFaultCodes(String faultCodes) {
    this.faultCodes = faultCodes;
  }

  public DeviceModel notifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
    return this;
  }

   /**
   * Notification EMail Address
   * @return notifyEmail
  **/
  @ApiModelProperty(value = "Notification EMail Address")
  public String getNotifyEmail() {
    return notifyEmail;
  }

  public void setNotifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
  }

  public DeviceModel equipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Equipment Type
   * @return equipmentType
  **/
  @ApiModelProperty(value = "Equipment Type")
  public String getEquipmentType() {
    return equipmentType;
  }

  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }

  public DeviceModel resetTime(Long resetTime) {
    this.resetTime = resetTime;
    return this;
  }

   /**
   * Reset time
   * @return resetTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Reset time")
  public Long getResetTime() {
    return resetTime;
  }

  public void setResetTime(Long resetTime) {
    this.resetTime = resetTime;
  }

  public DeviceModel installTime(Long installTime) {
    this.installTime = installTime;
    return this;
  }

   /**
   * Install time
   * @return installTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Install time")
  public Long getInstallTime() {
    return installTime;
  }

  public void setInstallTime(Long installTime) {
    this.installTime = installTime;
  }

  public DeviceModel lastStopTime(Long lastStopTime) {
    this.lastStopTime = lastStopTime;
    return this;
  }

   /**
   * Last stop time
   * @return lastStopTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last stop time")
  public Long getLastStopTime() {
    return lastStopTime;
  }

  public void setLastStopTime(Long lastStopTime) {
    this.lastStopTime = lastStopTime;
  }

  public DeviceModel lastStartTime(Long lastStartTime) {
    this.lastStartTime = lastStartTime;
    return this;
  }

   /**
   * Last start time
   * @return lastStartTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last start time")
  public Long getLastStartTime() {
    return lastStartTime;
  }

  public void setLastStartTime(Long lastStartTime) {
    this.lastStartTime = lastStartTime;
  }

  public DeviceModel lastIgnitionOnTime(Long lastIgnitionOnTime) {
    this.lastIgnitionOnTime = lastIgnitionOnTime;
    return this;
  }

   /**
   * Last ignition on time
   * @return lastIgnitionOnTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last ignition on time")
  public Long getLastIgnitionOnTime() {
    return lastIgnitionOnTime;
  }

  public void setLastIgnitionOnTime(Long lastIgnitionOnTime) {
    this.lastIgnitionOnTime = lastIgnitionOnTime;
  }

  public DeviceModel lastIgnitionOffTime(Long lastIgnitionOffTime) {
    this.lastIgnitionOffTime = lastIgnitionOffTime;
    return this;
  }

   /**
   * Last ignition off time
   * @return lastIgnitionOffTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last ignition off time")
  public Long getLastIgnitionOffTime() {
    return lastIgnitionOffTime;
  }

  public void setLastIgnitionOffTime(Long lastIgnitionOffTime) {
    this.lastIgnitionOffTime = lastIgnitionOffTime;
  }

  public DeviceModel creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Creation Time UTC
   * @return creationDate
  **/
  @ApiModelProperty(example = "1514707261000", value = "Creation Time UTC")
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }

  public DeviceModel lastServiceTime(Long lastServiceTime) {
    this.lastServiceTime = lastServiceTime;
    return this;
  }

   /**
   * Last Service Time UTC
   * @return lastServiceTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last Service Time UTC")
  public Long getLastServiceTime() {
    return lastServiceTime;
  }

  public void setLastServiceTime(Long lastServiceTime) {
    this.lastServiceTime = lastServiceTime;
  }

  public DeviceModel nextServiceTime(Long nextServiceTime) {
    this.nextServiceTime = nextServiceTime;
    return this;
  }

   /**
   * Next Service Time UTC
   * @return nextServiceTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Next Service Time UTC")
  public Long getNextServiceTime() {
    return nextServiceTime;
  }

  public void setNextServiceTime(Long nextServiceTime) {
    this.nextServiceTime = nextServiceTime;
  }

  public DeviceModel lastGPSTimestamp(Long lastGPSTimestamp) {
    this.lastGPSTimestamp = lastGPSTimestamp;
    return this;
  }

   /**
   * Last GPS Timestamp UTC
   * @return lastGPSTimestamp
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last GPS Timestamp UTC")
  public Long getLastGPSTimestamp() {
    return lastGPSTimestamp;
  }

  public void setLastGPSTimestamp(Long lastGPSTimestamp) {
    this.lastGPSTimestamp = lastGPSTimestamp;
  }

  public DeviceModel lastEventTimestamp(Long lastEventTimestamp) {
    this.lastEventTimestamp = lastEventTimestamp;
    return this;
  }

   /**
   * Last Event Timestamp UTC
   * @return lastEventTimestamp
  **/
  @ApiModelProperty(example = "1514707261000", value = "Last Event Timestamp UTC")
  public Long getLastEventTimestamp() {
    return lastEventTimestamp;
  }

  public void setLastEventTimestamp(Long lastEventTimestamp) {
    this.lastEventTimestamp = lastEventTimestamp;
  }

  public DeviceModel suspended(Boolean suspended) {
    this.suspended = suspended;
    return this;
  }

   /**
   * Is vehicle suspended?
   * @return suspended
  **/
  @ApiModelProperty(value = "Is vehicle suspended?")
  public Boolean isSuspended() {
    return suspended;
  }

  public void setSuspended(Boolean suspended) {
    this.suspended = suspended;
  }

  public DeviceModel notifyEnable(Boolean notifyEnable) {
    this.notifyEnable = notifyEnable;
    return this;
  }

   /**
   * Notification enabled?
   * @return notifyEnable
  **/
  @ApiModelProperty(value = "Notification enabled?")
  public Boolean isNotifyEnable() {
    return notifyEnable;
  }

  public void setNotifyEnable(Boolean notifyEnable) {
    this.notifyEnable = notifyEnable;
  }

  public DeviceModel maximumSpeed(Double maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
    return this;
  }

   /**
   * Maximum speed
   * @return maximumSpeed
  **/
  @ApiModelProperty(value = "Maximum speed")
  public Double getMaximumSpeed() {
    return maximumSpeed;
  }

  public void setMaximumSpeed(Double maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
  }

  public DeviceModel lastOdometerKM(Double lastOdometerKM) {
    this.lastOdometerKM = lastOdometerKM;
    return this;
  }

   /**
   * Reported odometer
   * @return lastOdometerKM
  **/
  @ApiModelProperty(value = "Reported odometer")
  public Double getLastOdometerKM() {
    return lastOdometerKM;
  }

  public void setLastOdometerKM(Double lastOdometerKM) {
    this.lastOdometerKM = lastOdometerKM;
  }

  public DeviceModel lastEngineHours(Double lastEngineHours) {
    this.lastEngineHours = lastEngineHours;
    return this;
  }

   /**
   * Last engine hours
   * @return lastEngineHours
  **/
  @ApiModelProperty(value = "Last engine hours")
  public Double getLastEngineHours() {
    return lastEngineHours;
  }

  public void setLastEngineHours(Double lastEngineHours) {
    this.lastEngineHours = lastEngineHours;
  }

  public DeviceModel engineHoursOffset(Double engineHoursOffset) {
    this.engineHoursOffset = engineHoursOffset;
    return this;
  }

   /**
   * Last engine offset
   * @return engineHoursOffset
  **/
  @ApiModelProperty(value = "Last engine offset")
  public Double getEngineHoursOffset() {
    return engineHoursOffset;
  }

  public void setEngineHoursOffset(Double engineHoursOffset) {
    this.engineHoursOffset = engineHoursOffset;
  }

  public DeviceModel odometerOffsetKM(Double odometerOffsetKM) {
    this.odometerOffsetKM = odometerOffsetKM;
    return this;
  }

   /**
   * Odometer offset KM
   * @return odometerOffsetKM
  **/
  @ApiModelProperty(value = "Odometer offset KM")
  public Double getOdometerOffsetKM() {
    return odometerOffsetKM;
  }

  public void setOdometerOffsetKM(Double odometerOffsetKM) {
    this.odometerOffsetKM = odometerOffsetKM;
  }

  public DeviceModel lastFuelLevel(Double lastFuelLevel) {
    this.lastFuelLevel = lastFuelLevel;
    return this;
  }

   /**
   * Last Fuel Level
   * @return lastFuelLevel
  **/
  @ApiModelProperty(value = "Last Fuel Level")
  public Double getLastFuelLevel() {
    return lastFuelLevel;
  }

  public void setLastFuelLevel(Double lastFuelLevel) {
    this.lastFuelLevel = lastFuelLevel;
  }

  public DeviceModel lastEngHoursMaint(Double lastEngHoursMaint) {
    this.lastEngHoursMaint = lastEngHoursMaint;
    return this;
  }

   /**
   * Last Engine Hours Maintenance
   * @return lastEngHoursMaint
  **/
  @ApiModelProperty(value = "Last Engine Hours Maintenance")
  public Double getLastEngHoursMaint() {
    return lastEngHoursMaint;
  }

  public void setLastEngHoursMaint(Double lastEngHoursMaint) {
    this.lastEngHoursMaint = lastEngHoursMaint;
  }

  public DeviceModel engHoursMaintInterval(Double engHoursMaintInterval) {
    this.engHoursMaintInterval = engHoursMaintInterval;
    return this;
  }

   /**
   * Last Engine Hours Maintenance Interval
   * @return engHoursMaintInterval
  **/
  @ApiModelProperty(value = "Last Engine Hours Maintenance Interval")
  public Double getEngHoursMaintInterval() {
    return engHoursMaintInterval;
  }

  public void setEngHoursMaintInterval(Double engHoursMaintInterval) {
    this.engHoursMaintInterval = engHoursMaintInterval;
  }

  public DeviceModel lastValidLatitude(Double lastValidLatitude) {
    this.lastValidLatitude = lastValidLatitude;
    return this;
  }

   /**
   * Last Valid Latitude
   * @return lastValidLatitude
  **/
  @ApiModelProperty(value = "Last Valid Latitude")
  public Double getLastValidLatitude() {
    return lastValidLatitude;
  }

  public void setLastValidLatitude(Double lastValidLatitude) {
    this.lastValidLatitude = lastValidLatitude;
  }

  public DeviceModel lastValidLongitude(Double lastValidLongitude) {
    this.lastValidLongitude = lastValidLongitude;
    return this;
  }

   /**
   * Last Valid Longitude
   * @return lastValidLongitude
  **/
  @ApiModelProperty(value = "Last Valid Longitude")
  public Double getLastValidLongitude() {
    return lastValidLongitude;
  }

  public void setLastValidLongitude(Double lastValidLongitude) {
    this.lastValidLongitude = lastValidLongitude;
  }

  public DeviceModel lastValidHeading(Double lastValidHeading) {
    this.lastValidHeading = lastValidHeading;
    return this;
  }

   /**
   * Last Valid Heading
   * @return lastValidHeading
  **/
  @ApiModelProperty(value = "Last Valid Heading")
  public Double getLastValidHeading() {
    return lastValidHeading;
  }

  public void setLastValidHeading(Double lastValidHeading) {
    this.lastValidHeading = lastValidHeading;
  }

  public DeviceModel statusCode(Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Status code
   * @return statusCode
  **/
  @ApiModelProperty(value = "Status code")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  public DeviceModel statusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
    return this;
  }

   /**
   * Status code text
   * @return statusCodeText
  **/
  @ApiModelProperty(value = "Status code text")
  public String getStatusCodeText() {
    return statusCodeText;
  }

  public void setStatusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
  }

  public DeviceModel statusColor(String statusColor) {
    this.statusColor = statusColor;
    return this;
  }

   /**
   * Status color
   * @return statusColor
  **/
  @ApiModelProperty(value = "Status color")
  public String getStatusColor() {
    return statusColor;
  }

  public void setStatusColor(String statusColor) {
    this.statusColor = statusColor;
  }

  public DeviceModel ignition(String ignition) {
    this.ignition = ignition;
    return this;
  }

   /**
   * Ignition state
   * @return ignition
  **/
  @ApiModelProperty(value = "Ignition state")
  public String getIgnition() {
    return ignition;
  }

  public void setIgnition(String ignition) {
    this.ignition = ignition;
  }

  public DeviceModel stopTime(String stopTime) {
    this.stopTime = stopTime;
    return this;
  }

   /**
   * Stop time
   * @return stopTime
  **/
  @ApiModelProperty(value = "Stop time")
  public String getStopTime() {
    return stopTime;
  }

  public void setStopTime(String stopTime) {
    this.stopTime = stopTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceModel deviceModel = (DeviceModel) o;
    return Objects.equals(this.accountID, deviceModel.accountID) &&
        Objects.equals(this.deviceId, deviceModel.deviceId) &&
        Objects.equals(this.uniqueId, deviceModel.uniqueId) &&
        Objects.equals(this.description, deviceModel.description) &&
        Objects.equals(this.displayName, deviceModel.displayName) &&
        Objects.equals(this.deviceCode, deviceModel.deviceCode) &&
        Objects.equals(this.deviceType, deviceModel.deviceType) &&
        Objects.equals(this.vehicleID, deviceModel.vehicleID) &&
        Objects.equals(this.vehicleMake, deviceModel.vehicleMake) &&
        Objects.equals(this.vehicleModel, deviceModel.vehicleModel) &&
        Objects.equals(this.licensePlate, deviceModel.licensePlate) &&
        Objects.equals(this.licenseExpiration, deviceModel.licenseExpiration) &&
        Objects.equals(this.reminderInterval, deviceModel.reminderInterval) &&
        Objects.equals(this.reminderMessage, deviceModel.reminderMessage) &&
        Objects.equals(this.maintenanceNotes, deviceModel.maintenanceNotes) &&
        Objects.equals(this.maintenanceInterval1, deviceModel.maintenanceInterval1) &&
        Objects.equals(this.lastMaintenance1, deviceModel.lastMaintenance1) &&
        Objects.equals(this.maintenanceInterval2, deviceModel.maintenanceInterval2) &&
        Objects.equals(this.lastMaintenance2, deviceModel.lastMaintenance2) &&
        Objects.equals(this.faultCodes, deviceModel.faultCodes) &&
        Objects.equals(this.notifyEmail, deviceModel.notifyEmail) &&
        Objects.equals(this.equipmentType, deviceModel.equipmentType) &&
        Objects.equals(this.resetTime, deviceModel.resetTime) &&
        Objects.equals(this.installTime, deviceModel.installTime) &&
        Objects.equals(this.lastStopTime, deviceModel.lastStopTime) &&
        Objects.equals(this.lastStartTime, deviceModel.lastStartTime) &&
        Objects.equals(this.lastIgnitionOnTime, deviceModel.lastIgnitionOnTime) &&
        Objects.equals(this.lastIgnitionOffTime, deviceModel.lastIgnitionOffTime) &&
        Objects.equals(this.creationDate, deviceModel.creationDate) &&
        Objects.equals(this.lastServiceTime, deviceModel.lastServiceTime) &&
        Objects.equals(this.nextServiceTime, deviceModel.nextServiceTime) &&
        Objects.equals(this.lastGPSTimestamp, deviceModel.lastGPSTimestamp) &&
        Objects.equals(this.lastEventTimestamp, deviceModel.lastEventTimestamp) &&
        Objects.equals(this.suspended, deviceModel.suspended) &&
        Objects.equals(this.notifyEnable, deviceModel.notifyEnable) &&
        Objects.equals(this.maximumSpeed, deviceModel.maximumSpeed) &&
        Objects.equals(this.lastOdometerKM, deviceModel.lastOdometerKM) &&
        Objects.equals(this.lastEngineHours, deviceModel.lastEngineHours) &&
        Objects.equals(this.engineHoursOffset, deviceModel.engineHoursOffset) &&
        Objects.equals(this.odometerOffsetKM, deviceModel.odometerOffsetKM) &&
        Objects.equals(this.lastFuelLevel, deviceModel.lastFuelLevel) &&
        Objects.equals(this.lastEngHoursMaint, deviceModel.lastEngHoursMaint) &&
        Objects.equals(this.engHoursMaintInterval, deviceModel.engHoursMaintInterval) &&
        Objects.equals(this.lastValidLatitude, deviceModel.lastValidLatitude) &&
        Objects.equals(this.lastValidLongitude, deviceModel.lastValidLongitude) &&
        Objects.equals(this.lastValidHeading, deviceModel.lastValidHeading) &&
        Objects.equals(this.statusCode, deviceModel.statusCode) &&
        Objects.equals(this.statusCodeText, deviceModel.statusCodeText) &&
        Objects.equals(this.statusColor, deviceModel.statusColor) &&
        Objects.equals(this.ignition, deviceModel.ignition) &&
        Objects.equals(this.stopTime, deviceModel.stopTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountID, deviceId, uniqueId, description, displayName, deviceCode, deviceType, vehicleID, vehicleMake, vehicleModel, licensePlate, licenseExpiration, reminderInterval, reminderMessage, maintenanceNotes, maintenanceInterval1, lastMaintenance1, maintenanceInterval2, lastMaintenance2, faultCodes, notifyEmail, equipmentType, resetTime, installTime, lastStopTime, lastStartTime, lastIgnitionOnTime, lastIgnitionOffTime, creationDate, lastServiceTime, nextServiceTime, lastGPSTimestamp, lastEventTimestamp, suspended, notifyEnable, maximumSpeed, lastOdometerKM, lastEngineHours, engineHoursOffset, odometerOffsetKM, lastFuelLevel, lastEngHoursMaint, engHoursMaintInterval, lastValidLatitude, lastValidLongitude, lastValidHeading, statusCode, statusCodeText, statusColor, ignition, stopTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceModel {\n");
    
    sb.append("    accountID: ").append(toIndentedString(accountID)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    deviceCode: ").append(toIndentedString(deviceCode)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    vehicleID: ").append(toIndentedString(vehicleID)).append("\n");
    sb.append("    vehicleMake: ").append(toIndentedString(vehicleMake)).append("\n");
    sb.append("    vehicleModel: ").append(toIndentedString(vehicleModel)).append("\n");
    sb.append("    licensePlate: ").append(toIndentedString(licensePlate)).append("\n");
    sb.append("    licenseExpiration: ").append(toIndentedString(licenseExpiration)).append("\n");
    sb.append("    reminderInterval: ").append(toIndentedString(reminderInterval)).append("\n");
    sb.append("    reminderMessage: ").append(toIndentedString(reminderMessage)).append("\n");
    sb.append("    maintenanceNotes: ").append(toIndentedString(maintenanceNotes)).append("\n");
    sb.append("    maintenanceInterval1: ").append(toIndentedString(maintenanceInterval1)).append("\n");
    sb.append("    lastMaintenance1: ").append(toIndentedString(lastMaintenance1)).append("\n");
    sb.append("    maintenanceInterval2: ").append(toIndentedString(maintenanceInterval2)).append("\n");
    sb.append("    lastMaintenance2: ").append(toIndentedString(lastMaintenance2)).append("\n");
    sb.append("    faultCodes: ").append(toIndentedString(faultCodes)).append("\n");
    sb.append("    notifyEmail: ").append(toIndentedString(notifyEmail)).append("\n");
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    resetTime: ").append(toIndentedString(resetTime)).append("\n");
    sb.append("    installTime: ").append(toIndentedString(installTime)).append("\n");
    sb.append("    lastStopTime: ").append(toIndentedString(lastStopTime)).append("\n");
    sb.append("    lastStartTime: ").append(toIndentedString(lastStartTime)).append("\n");
    sb.append("    lastIgnitionOnTime: ").append(toIndentedString(lastIgnitionOnTime)).append("\n");
    sb.append("    lastIgnitionOffTime: ").append(toIndentedString(lastIgnitionOffTime)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    lastServiceTime: ").append(toIndentedString(lastServiceTime)).append("\n");
    sb.append("    nextServiceTime: ").append(toIndentedString(nextServiceTime)).append("\n");
    sb.append("    lastGPSTimestamp: ").append(toIndentedString(lastGPSTimestamp)).append("\n");
    sb.append("    lastEventTimestamp: ").append(toIndentedString(lastEventTimestamp)).append("\n");
    sb.append("    suspended: ").append(toIndentedString(suspended)).append("\n");
    sb.append("    notifyEnable: ").append(toIndentedString(notifyEnable)).append("\n");
    sb.append("    maximumSpeed: ").append(toIndentedString(maximumSpeed)).append("\n");
    sb.append("    lastOdometerKM: ").append(toIndentedString(lastOdometerKM)).append("\n");
    sb.append("    lastEngineHours: ").append(toIndentedString(lastEngineHours)).append("\n");
    sb.append("    engineHoursOffset: ").append(toIndentedString(engineHoursOffset)).append("\n");
    sb.append("    odometerOffsetKM: ").append(toIndentedString(odometerOffsetKM)).append("\n");
    sb.append("    lastFuelLevel: ").append(toIndentedString(lastFuelLevel)).append("\n");
    sb.append("    lastEngHoursMaint: ").append(toIndentedString(lastEngHoursMaint)).append("\n");
    sb.append("    engHoursMaintInterval: ").append(toIndentedString(engHoursMaintInterval)).append("\n");
    sb.append("    lastValidLatitude: ").append(toIndentedString(lastValidLatitude)).append("\n");
    sb.append("    lastValidLongitude: ").append(toIndentedString(lastValidLongitude)).append("\n");
    sb.append("    lastValidHeading: ").append(toIndentedString(lastValidHeading)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusCodeText: ").append(toIndentedString(statusCodeText)).append("\n");
    sb.append("    statusColor: ").append(toIndentedString(statusColor)).append("\n");
    sb.append("    ignition: ").append(toIndentedString(ignition)).append("\n");
    sb.append("    stopTime: ").append(toIndentedString(stopTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

