/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EventDataModel
 */

public class EventDataModel {
  @SerializedName("acceleration")
  private Double acceleration = null;

  @SerializedName("accelerometerXYZ")
  private String accelerometerXYZ = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("altitude")
  private Double altitude = null;

  @SerializedName("batteryLevel")
  private Double batteryLevel = null;

  @SerializedName("batteryVolts")
  private Double batteryVolts = null;

  @SerializedName("city")
  private String city = null;

  @SerializedName("country")
  private String country = null;

  @SerializedName("creationTime")
  private Double creationTime = null;

  @SerializedName("deceleration")
  private Double deceleration = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("driverId")
  private String driverId = null;

  @SerializedName("engineHours")
  private Double engineHours = null;

  @SerializedName("faultCode")
  private String faultCode = null;

  @SerializedName("fuelLevel")
  private Double fuelLevel = null;

  @SerializedName("geozoneId")
  private String geozoneId = null;

  @SerializedName("gpsAge")
  private Long gpsAge = null;

  @SerializedName("hdop")
  private Double hdop = null;

  @SerializedName("heading")
  private Double heading = null;

  @SerializedName("ignition")
  private String ignition = null;

  @SerializedName("j1708Fault")
  private Long j1708Fault = null;

  @SerializedName("latitude")
  private String latitude = null;

  @SerializedName("longitude")
  private String longitude = null;

  @SerializedName("malfunctionLamp")
  private Boolean malfunctionLamp = null;

  @SerializedName("odometerKm")
  private Double odometerKm = null;

  @SerializedName("odometerOffsetKm")
  private Double odometerOffsetKm = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("satelliteCount")
  private Integer satelliteCount = null;

  @SerializedName("signalStrength")
  private Double signalStrength = null;

  @SerializedName("speedKmh")
  private Double speedKmh = null;

  @SerializedName("speedLimitKPH")
  private Double speedLimitKPH = null;

  @SerializedName("speedMph")
  private Double speedMph = null;

  @SerializedName("stateProvince")
  private String stateProvince = null;

  @SerializedName("statusCode")
  private Integer statusCode = null;

  @SerializedName("statusCodeText")
  private String statusCodeText = null;

  @SerializedName("statusColor")
  private String statusColor = null;

  @SerializedName("stopTime")
  private String stopTime = null;

  @SerializedName("streetAddress")
  private String streetAddress = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  @SerializedName("vbatteryVolts")
  private Double vbatteryVolts = null;

  public EventDataModel acceleration(Double acceleration) {
    this.acceleration = acceleration;
    return this;
  }

   /**
   * Get acceleration
   * @return acceleration
  **/
  @ApiModelProperty(value = "")
  public Double getAcceleration() {
    return acceleration;
  }

  public void setAcceleration(Double acceleration) {
    this.acceleration = acceleration;
  }

  public EventDataModel accelerometerXYZ(String accelerometerXYZ) {
    this.accelerometerXYZ = accelerometerXYZ;
    return this;
  }

   /**
   * Get accelerometerXYZ
   * @return accelerometerXYZ
  **/
  @ApiModelProperty(value = "")
  public String getAccelerometerXYZ() {
    return accelerometerXYZ;
  }

  public void setAccelerometerXYZ(String accelerometerXYZ) {
    this.accelerometerXYZ = accelerometerXYZ;
  }

  public EventDataModel address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public EventDataModel altitude(Double altitude) {
    this.altitude = altitude;
    return this;
  }

   /**
   * Get altitude
   * @return altitude
  **/
  @ApiModelProperty(value = "")
  public Double getAltitude() {
    return altitude;
  }

  public void setAltitude(Double altitude) {
    this.altitude = altitude;
  }

  public EventDataModel batteryLevel(Double batteryLevel) {
    this.batteryLevel = batteryLevel;
    return this;
  }

   /**
   * Get batteryLevel
   * @return batteryLevel
  **/
  @ApiModelProperty(value = "")
  public Double getBatteryLevel() {
    return batteryLevel;
  }

  public void setBatteryLevel(Double batteryLevel) {
    this.batteryLevel = batteryLevel;
  }

  public EventDataModel batteryVolts(Double batteryVolts) {
    this.batteryVolts = batteryVolts;
    return this;
  }

   /**
   * Get batteryVolts
   * @return batteryVolts
  **/
  @ApiModelProperty(value = "")
  public Double getBatteryVolts() {
    return batteryVolts;
  }

  public void setBatteryVolts(Double batteryVolts) {
    this.batteryVolts = batteryVolts;
  }

  public EventDataModel city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @ApiModelProperty(value = "")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public EventDataModel country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public EventDataModel creationTime(Double creationTime) {
    this.creationTime = creationTime;
    return this;
  }

   /**
   * Get creationTime
   * @return creationTime
  **/
  @ApiModelProperty(value = "")
  public Double getCreationTime() {
    return creationTime;
  }

  public void setCreationTime(Double creationTime) {
    this.creationTime = creationTime;
  }

  public EventDataModel deceleration(Double deceleration) {
    this.deceleration = deceleration;
    return this;
  }

   /**
   * Get deceleration
   * @return deceleration
  **/
  @ApiModelProperty(value = "")
  public Double getDeceleration() {
    return deceleration;
  }

  public void setDeceleration(Double deceleration) {
    this.deceleration = deceleration;
  }

  public EventDataModel deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public EventDataModel driverId(String driverId) {
    this.driverId = driverId;
    return this;
  }

   /**
   * Get driverId
   * @return driverId
  **/
  @ApiModelProperty(value = "")
  public String getDriverId() {
    return driverId;
  }

  public void setDriverId(String driverId) {
    this.driverId = driverId;
  }

  public EventDataModel engineHours(Double engineHours) {
    this.engineHours = engineHours;
    return this;
  }

   /**
   * Get engineHours
   * @return engineHours
  **/
  @ApiModelProperty(value = "")
  public Double getEngineHours() {
    return engineHours;
  }

  public void setEngineHours(Double engineHours) {
    this.engineHours = engineHours;
  }

  public EventDataModel faultCode(String faultCode) {
    this.faultCode = faultCode;
    return this;
  }

   /**
   * Get faultCode
   * @return faultCode
  **/
  @ApiModelProperty(value = "")
  public String getFaultCode() {
    return faultCode;
  }

  public void setFaultCode(String faultCode) {
    this.faultCode = faultCode;
  }

  public EventDataModel fuelLevel(Double fuelLevel) {
    this.fuelLevel = fuelLevel;
    return this;
  }

   /**
   * Get fuelLevel
   * @return fuelLevel
  **/
  @ApiModelProperty(value = "")
  public Double getFuelLevel() {
    return fuelLevel;
  }

  public void setFuelLevel(Double fuelLevel) {
    this.fuelLevel = fuelLevel;
  }

  public EventDataModel geozoneId(String geozoneId) {
    this.geozoneId = geozoneId;
    return this;
  }

   /**
   * Get geozoneId
   * @return geozoneId
  **/
  @ApiModelProperty(value = "")
  public String getGeozoneId() {
    return geozoneId;
  }

  public void setGeozoneId(String geozoneId) {
    this.geozoneId = geozoneId;
  }

  public EventDataModel gpsAge(Long gpsAge) {
    this.gpsAge = gpsAge;
    return this;
  }

   /**
   * Get gpsAge
   * @return gpsAge
  **/
  @ApiModelProperty(value = "")
  public Long getGpsAge() {
    return gpsAge;
  }

  public void setGpsAge(Long gpsAge) {
    this.gpsAge = gpsAge;
  }

  public EventDataModel hdop(Double hdop) {
    this.hdop = hdop;
    return this;
  }

   /**
   * Get hdop
   * @return hdop
  **/
  @ApiModelProperty(value = "")
  public Double getHdop() {
    return hdop;
  }

  public void setHdop(Double hdop) {
    this.hdop = hdop;
  }

  public EventDataModel heading(Double heading) {
    this.heading = heading;
    return this;
  }

   /**
   * Get heading
   * @return heading
  **/
  @ApiModelProperty(value = "")
  public Double getHeading() {
    return heading;
  }

  public void setHeading(Double heading) {
    this.heading = heading;
  }

  public EventDataModel ignition(String ignition) {
    this.ignition = ignition;
    return this;
  }

   /**
   * Get ignition
   * @return ignition
  **/
  @ApiModelProperty(value = "")
  public String getIgnition() {
    return ignition;
  }

  public void setIgnition(String ignition) {
    this.ignition = ignition;
  }

  public EventDataModel j1708Fault(Long j1708Fault) {
    this.j1708Fault = j1708Fault;
    return this;
  }

   /**
   * Get j1708Fault
   * @return j1708Fault
  **/
  @ApiModelProperty(value = "")
  public Long getJ1708Fault() {
    return j1708Fault;
  }

  public void setJ1708Fault(Long j1708Fault) {
    this.j1708Fault = j1708Fault;
  }

  public EventDataModel latitude(String latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @ApiModelProperty(value = "")
  public String getLatitude() {
    return latitude;
  }

  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }

  public EventDataModel longitude(String longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @ApiModelProperty(value = "")
  public String getLongitude() {
    return longitude;
  }

  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }

  public EventDataModel malfunctionLamp(Boolean malfunctionLamp) {
    this.malfunctionLamp = malfunctionLamp;
    return this;
  }

   /**
   * Get malfunctionLamp
   * @return malfunctionLamp
  **/
  @ApiModelProperty(value = "")
  public Boolean isMalfunctionLamp() {
    return malfunctionLamp;
  }

  public void setMalfunctionLamp(Boolean malfunctionLamp) {
    this.malfunctionLamp = malfunctionLamp;
  }

  public EventDataModel odometerKm(Double odometerKm) {
    this.odometerKm = odometerKm;
    return this;
  }

   /**
   * Get odometerKm
   * @return odometerKm
  **/
  @ApiModelProperty(value = "")
  public Double getOdometerKm() {
    return odometerKm;
  }

  public void setOdometerKm(Double odometerKm) {
    this.odometerKm = odometerKm;
  }

  public EventDataModel odometerOffsetKm(Double odometerOffsetKm) {
    this.odometerOffsetKm = odometerOffsetKm;
    return this;
  }

   /**
   * Get odometerOffsetKm
   * @return odometerOffsetKm
  **/
  @ApiModelProperty(value = "")
  public Double getOdometerOffsetKm() {
    return odometerOffsetKm;
  }

  public void setOdometerOffsetKm(Double odometerOffsetKm) {
    this.odometerOffsetKm = odometerOffsetKm;
  }

  public EventDataModel postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @ApiModelProperty(value = "")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public EventDataModel satelliteCount(Integer satelliteCount) {
    this.satelliteCount = satelliteCount;
    return this;
  }

   /**
   * Get satelliteCount
   * @return satelliteCount
  **/
  @ApiModelProperty(value = "")
  public Integer getSatelliteCount() {
    return satelliteCount;
  }

  public void setSatelliteCount(Integer satelliteCount) {
    this.satelliteCount = satelliteCount;
  }

  public EventDataModel signalStrength(Double signalStrength) {
    this.signalStrength = signalStrength;
    return this;
  }

   /**
   * Get signalStrength
   * @return signalStrength
  **/
  @ApiModelProperty(value = "")
  public Double getSignalStrength() {
    return signalStrength;
  }

  public void setSignalStrength(Double signalStrength) {
    this.signalStrength = signalStrength;
  }

  public EventDataModel speedKmh(Double speedKmh) {
    this.speedKmh = speedKmh;
    return this;
  }

   /**
   * Get speedKmh
   * @return speedKmh
  **/
  @ApiModelProperty(value = "")
  public Double getSpeedKmh() {
    return speedKmh;
  }

  public void setSpeedKmh(Double speedKmh) {
    this.speedKmh = speedKmh;
  }

  public EventDataModel speedLimitKPH(Double speedLimitKPH) {
    this.speedLimitKPH = speedLimitKPH;
    return this;
  }

   /**
   * Get speedLimitKPH
   * @return speedLimitKPH
  **/
  @ApiModelProperty(value = "")
  public Double getSpeedLimitKPH() {
    return speedLimitKPH;
  }

  public void setSpeedLimitKPH(Double speedLimitKPH) {
    this.speedLimitKPH = speedLimitKPH;
  }

  public EventDataModel speedMph(Double speedMph) {
    this.speedMph = speedMph;
    return this;
  }

   /**
   * Get speedMph
   * @return speedMph
  **/
  @ApiModelProperty(value = "")
  public Double getSpeedMph() {
    return speedMph;
  }

  public void setSpeedMph(Double speedMph) {
    this.speedMph = speedMph;
  }

  public EventDataModel stateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * Get stateProvince
   * @return stateProvince
  **/
  @ApiModelProperty(value = "")
  public String getStateProvince() {
    return stateProvince;
  }

  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }

  public EventDataModel statusCode(Integer statusCode) {
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Get statusCode
   * @return statusCode
  **/
  @ApiModelProperty(value = "")
  public Integer getStatusCode() {
    return statusCode;
  }

  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }

  public EventDataModel statusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
    return this;
  }

   /**
   * Get statusCodeText
   * @return statusCodeText
  **/
  @ApiModelProperty(value = "")
  public String getStatusCodeText() {
    return statusCodeText;
  }

  public void setStatusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
  }

  public EventDataModel statusColor(String statusColor) {
    this.statusColor = statusColor;
    return this;
  }

   /**
   * Get statusColor
   * @return statusColor
  **/
  @ApiModelProperty(value = "")
  public String getStatusColor() {
    return statusColor;
  }

  public void setStatusColor(String statusColor) {
    this.statusColor = statusColor;
  }

  public EventDataModel stopTime(String stopTime) {
    this.stopTime = stopTime;
    return this;
  }

   /**
   * Get stopTime
   * @return stopTime
  **/
  @ApiModelProperty(value = "")
  public String getStopTime() {
    return stopTime;
  }

  public void setStopTime(String stopTime) {
    this.stopTime = stopTime;
  }

  public EventDataModel streetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

   /**
   * Get streetAddress
   * @return streetAddress
  **/
  @ApiModelProperty(value = "")
  public String getStreetAddress() {
    return streetAddress;
  }

  public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
  }

  public EventDataModel timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public EventDataModel vbatteryVolts(Double vbatteryVolts) {
    this.vbatteryVolts = vbatteryVolts;
    return this;
  }

   /**
   * Get vbatteryVolts
   * @return vbatteryVolts
  **/
  @ApiModelProperty(value = "")
  public Double getVbatteryVolts() {
    return vbatteryVolts;
  }

  public void setVbatteryVolts(Double vbatteryVolts) {
    this.vbatteryVolts = vbatteryVolts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventDataModel eventDataModel = (EventDataModel) o;
    return Objects.equals(this.acceleration, eventDataModel.acceleration) &&
        Objects.equals(this.accelerometerXYZ, eventDataModel.accelerometerXYZ) &&
        Objects.equals(this.address, eventDataModel.address) &&
        Objects.equals(this.altitude, eventDataModel.altitude) &&
        Objects.equals(this.batteryLevel, eventDataModel.batteryLevel) &&
        Objects.equals(this.batteryVolts, eventDataModel.batteryVolts) &&
        Objects.equals(this.city, eventDataModel.city) &&
        Objects.equals(this.country, eventDataModel.country) &&
        Objects.equals(this.creationTime, eventDataModel.creationTime) &&
        Objects.equals(this.deceleration, eventDataModel.deceleration) &&
        Objects.equals(this.deviceId, eventDataModel.deviceId) &&
        Objects.equals(this.driverId, eventDataModel.driverId) &&
        Objects.equals(this.engineHours, eventDataModel.engineHours) &&
        Objects.equals(this.faultCode, eventDataModel.faultCode) &&
        Objects.equals(this.fuelLevel, eventDataModel.fuelLevel) &&
        Objects.equals(this.geozoneId, eventDataModel.geozoneId) &&
        Objects.equals(this.gpsAge, eventDataModel.gpsAge) &&
        Objects.equals(this.hdop, eventDataModel.hdop) &&
        Objects.equals(this.heading, eventDataModel.heading) &&
        Objects.equals(this.ignition, eventDataModel.ignition) &&
        Objects.equals(this.j1708Fault, eventDataModel.j1708Fault) &&
        Objects.equals(this.latitude, eventDataModel.latitude) &&
        Objects.equals(this.longitude, eventDataModel.longitude) &&
        Objects.equals(this.malfunctionLamp, eventDataModel.malfunctionLamp) &&
        Objects.equals(this.odometerKm, eventDataModel.odometerKm) &&
        Objects.equals(this.odometerOffsetKm, eventDataModel.odometerOffsetKm) &&
        Objects.equals(this.postalCode, eventDataModel.postalCode) &&
        Objects.equals(this.satelliteCount, eventDataModel.satelliteCount) &&
        Objects.equals(this.signalStrength, eventDataModel.signalStrength) &&
        Objects.equals(this.speedKmh, eventDataModel.speedKmh) &&
        Objects.equals(this.speedLimitKPH, eventDataModel.speedLimitKPH) &&
        Objects.equals(this.speedMph, eventDataModel.speedMph) &&
        Objects.equals(this.stateProvince, eventDataModel.stateProvince) &&
        Objects.equals(this.statusCode, eventDataModel.statusCode) &&
        Objects.equals(this.statusCodeText, eventDataModel.statusCodeText) &&
        Objects.equals(this.statusColor, eventDataModel.statusColor) &&
        Objects.equals(this.stopTime, eventDataModel.stopTime) &&
        Objects.equals(this.streetAddress, eventDataModel.streetAddress) &&
        Objects.equals(this.timestamp, eventDataModel.timestamp) &&
        Objects.equals(this.vbatteryVolts, eventDataModel.vbatteryVolts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceleration, accelerometerXYZ, address, altitude, batteryLevel, batteryVolts, city, country, creationTime, deceleration, deviceId, driverId, engineHours, faultCode, fuelLevel, geozoneId, gpsAge, hdop, heading, ignition, j1708Fault, latitude, longitude, malfunctionLamp, odometerKm, odometerOffsetKm, postalCode, satelliteCount, signalStrength, speedKmh, speedLimitKPH, speedMph, stateProvince, statusCode, statusCodeText, statusColor, stopTime, streetAddress, timestamp, vbatteryVolts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventDataModel {\n");
    
    sb.append("    acceleration: ").append(toIndentedString(acceleration)).append("\n");
    sb.append("    accelerometerXYZ: ").append(toIndentedString(accelerometerXYZ)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    altitude: ").append(toIndentedString(altitude)).append("\n");
    sb.append("    batteryLevel: ").append(toIndentedString(batteryLevel)).append("\n");
    sb.append("    batteryVolts: ").append(toIndentedString(batteryVolts)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    creationTime: ").append(toIndentedString(creationTime)).append("\n");
    sb.append("    deceleration: ").append(toIndentedString(deceleration)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    driverId: ").append(toIndentedString(driverId)).append("\n");
    sb.append("    engineHours: ").append(toIndentedString(engineHours)).append("\n");
    sb.append("    faultCode: ").append(toIndentedString(faultCode)).append("\n");
    sb.append("    fuelLevel: ").append(toIndentedString(fuelLevel)).append("\n");
    sb.append("    geozoneId: ").append(toIndentedString(geozoneId)).append("\n");
    sb.append("    gpsAge: ").append(toIndentedString(gpsAge)).append("\n");
    sb.append("    hdop: ").append(toIndentedString(hdop)).append("\n");
    sb.append("    heading: ").append(toIndentedString(heading)).append("\n");
    sb.append("    ignition: ").append(toIndentedString(ignition)).append("\n");
    sb.append("    j1708Fault: ").append(toIndentedString(j1708Fault)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    malfunctionLamp: ").append(toIndentedString(malfunctionLamp)).append("\n");
    sb.append("    odometerKm: ").append(toIndentedString(odometerKm)).append("\n");
    sb.append("    odometerOffsetKm: ").append(toIndentedString(odometerOffsetKm)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    satelliteCount: ").append(toIndentedString(satelliteCount)).append("\n");
    sb.append("    signalStrength: ").append(toIndentedString(signalStrength)).append("\n");
    sb.append("    speedKmh: ").append(toIndentedString(speedKmh)).append("\n");
    sb.append("    speedLimitKPH: ").append(toIndentedString(speedLimitKPH)).append("\n");
    sb.append("    speedMph: ").append(toIndentedString(speedMph)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusCodeText: ").append(toIndentedString(statusCodeText)).append("\n");
    sb.append("    statusColor: ").append(toIndentedString(statusColor)).append("\n");
    sb.append("    stopTime: ").append(toIndentedString(stopTime)).append("\n");
    sb.append("    streetAddress: ").append(toIndentedString(streetAddress)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    vbatteryVolts: ").append(toIndentedString(vbatteryVolts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

