/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * EventDataSetModel
 */

public class EventDataSetModel {
  @SerializedName("description")
  private String description = null;

  @SerializedName("driverId")
  private String driverId = null;

  @SerializedName("eventData")
  private List<EventDataModel> eventData = null;

  @SerializedName("id")
  private String id = null;

  public EventDataSetModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EventDataSetModel driverId(String driverId) {
    this.driverId = driverId;
    return this;
  }

   /**
   * Get driverId
   * @return driverId
  **/
  @ApiModelProperty(value = "")
  public String getDriverId() {
    return driverId;
  }

  public void setDriverId(String driverId) {
    this.driverId = driverId;
  }

  public EventDataSetModel eventData(List<EventDataModel> eventData) {
    this.eventData = eventData;
    return this;
  }

  public EventDataSetModel addEventDataItem(EventDataModel eventDataItem) {
    if (this.eventData == null) {
      this.eventData = new ArrayList<EventDataModel>();
    }
    this.eventData.add(eventDataItem);
    return this;
  }

   /**
   * Get eventData
   * @return eventData
  **/
  @ApiModelProperty(value = "")
  public List<EventDataModel> getEventData() {
    return eventData;
  }

  public void setEventData(List<EventDataModel> eventData) {
    this.eventData = eventData;
  }

  public EventDataSetModel id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventDataSetModel eventDataSetModel = (EventDataSetModel) o;
    return Objects.equals(this.description, eventDataSetModel.description) &&
        Objects.equals(this.driverId, eventDataSetModel.driverId) &&
        Objects.equals(this.eventData, eventDataSetModel.eventData) &&
        Objects.equals(this.id, eventDataSetModel.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, driverId, eventData, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventDataSetModel {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    driverId: ").append(toIndentedString(driverId)).append("\n");
    sb.append("    eventData: ").append(toIndentedString(eventData)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

