/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GeozoneActivityModel
 */

public class GeozoneActivityModel {
  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("geozoneId")
  private String geozoneId = null;

  @SerializedName("statusCodeText")
  private String statusCodeText = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  public GeozoneActivityModel accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public GeozoneActivityModel deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Get deviceId
   * @return deviceId
  **/
  @ApiModelProperty(value = "")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public GeozoneActivityModel geozoneId(String geozoneId) {
    this.geozoneId = geozoneId;
    return this;
  }

   /**
   * Get geozoneId
   * @return geozoneId
  **/
  @ApiModelProperty(value = "")
  public String getGeozoneId() {
    return geozoneId;
  }

  public void setGeozoneId(String geozoneId) {
    this.geozoneId = geozoneId;
  }

  public GeozoneActivityModel statusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
    return this;
  }

   /**
   * Get statusCodeText
   * @return statusCodeText
  **/
  @ApiModelProperty(value = "")
  public String getStatusCodeText() {
    return statusCodeText;
  }

  public void setStatusCodeText(String statusCodeText) {
    this.statusCodeText = statusCodeText;
  }

  public GeozoneActivityModel timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeozoneActivityModel geozoneActivityModel = (GeozoneActivityModel) o;
    return Objects.equals(this.accountId, geozoneActivityModel.accountId) &&
        Objects.equals(this.deviceId, geozoneActivityModel.deviceId) &&
        Objects.equals(this.geozoneId, geozoneActivityModel.geozoneId) &&
        Objects.equals(this.statusCodeText, geozoneActivityModel.statusCodeText) &&
        Objects.equals(this.timestamp, geozoneActivityModel.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, deviceId, geozoneId, statusCodeText, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeozoneActivityModel {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    geozoneId: ").append(toIndentedString(geozoneId)).append("\n");
    sb.append("    statusCodeText: ").append(toIndentedString(statusCodeText)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

