/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RefreshTokenRequestModel
 */

public class RefreshTokenRequestModel {
  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("refreshTokenString")
  private String refreshTokenString = null;

  @SerializedName("userId")
  private String userId = null;

  public RefreshTokenRequestModel accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public RefreshTokenRequestModel refreshTokenString(String refreshTokenString) {
    this.refreshTokenString = refreshTokenString;
    return this;
  }

   /**
   * Get refreshTokenString
   * @return refreshTokenString
  **/
  @ApiModelProperty(value = "")
  public String getRefreshTokenString() {
    return refreshTokenString;
  }

  public void setRefreshTokenString(String refreshTokenString) {
    this.refreshTokenString = refreshTokenString;
  }

  public RefreshTokenRequestModel userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefreshTokenRequestModel refreshTokenRequestModel = (RefreshTokenRequestModel) o;
    return Objects.equals(this.accountId, refreshTokenRequestModel.accountId) &&
        Objects.equals(this.refreshTokenString, refreshTokenRequestModel.refreshTokenString) &&
        Objects.equals(this.userId, refreshTokenRequestModel.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, refreshTokenString, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefreshTokenRequestModel {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    refreshTokenString: ").append(toIndentedString(refreshTokenString)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

