/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdateDeviceModel
 */

public class UpdateDeviceModel {
  @SerializedName("deviceId")
  private String deviceId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("shortName")
  private String shortName = null;

  @SerializedName("vehicleId")
  private String vehicleId = null;

  @SerializedName("vehicleMake")
  private String vehicleMake = null;

  @SerializedName("vehicleModel")
  private String vehicleModel = null;

  @SerializedName("licensePlate")
  private String licensePlate = null;

  @SerializedName("licenseExpiration")
  private Long licenseExpiration = null;

  @SerializedName("reminderInterval")
  private String reminderInterval = null;

  @SerializedName("reminderMessage")
  private String reminderMessage = null;

  @SerializedName("maintenanceNotes")
  private String maintenanceNotes = null;

  @SerializedName("maintenanceInterval1")
  private Double maintenanceInterval1 = null;

  @SerializedName("lastMaintenance1")
  private Double lastMaintenance1 = null;

  @SerializedName("maintenanceInterval2")
  private Double maintenanceInterval2 = null;

  @SerializedName("notifyEmail")
  private String notifyEmail = null;

  @SerializedName("faultCodes")
  private String faultCodes = null;

  @SerializedName("equipmentType")
  private String equipmentType = null;

  @SerializedName("nextServiceTime")
  private Long nextServiceTime = null;

  @SerializedName("maximumSpeed")
  private Double maximumSpeed = null;

  @SerializedName("notifyEnable")
  private Boolean notifyEnable = null;

  @SerializedName("reportedOdometer")
  private Double reportedOdometer = null;

  @SerializedName("reportedEngineHours")
  private Double reportedEngineHours = null;

  @SerializedName("lastEngHoursMaint")
  private Double lastEngHoursMaint = null;

  @SerializedName("engHoursMaintInterval")
  private Double engHoursMaintInterval = null;

  public UpdateDeviceModel deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

   /**
   * Device ID
   * @return deviceId
  **/
  @ApiModelProperty(required = true, value = "Device ID")
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }

  public UpdateDeviceModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Device Description
   * @return description
  **/
  @ApiModelProperty(value = "Device Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UpdateDeviceModel shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Display Name
   * @return shortName
  **/
  @ApiModelProperty(value = "Display Name")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public UpdateDeviceModel vehicleId(String vehicleId) {
    this.vehicleId = vehicleId;
    return this;
  }

   /**
   * VIN
   * @return vehicleId
  **/
  @ApiModelProperty(value = "VIN")
  public String getVehicleId() {
    return vehicleId;
  }

  public void setVehicleId(String vehicleId) {
    this.vehicleId = vehicleId;
  }

  public UpdateDeviceModel vehicleMake(String vehicleMake) {
    this.vehicleMake = vehicleMake;
    return this;
  }

   /**
   * Vehicle Make
   * @return vehicleMake
  **/
  @ApiModelProperty(value = "Vehicle Make")
  public String getVehicleMake() {
    return vehicleMake;
  }

  public void setVehicleMake(String vehicleMake) {
    this.vehicleMake = vehicleMake;
  }

  public UpdateDeviceModel vehicleModel(String vehicleModel) {
    this.vehicleModel = vehicleModel;
    return this;
  }

   /**
   * Vehicle Model
   * @return vehicleModel
  **/
  @ApiModelProperty(value = "Vehicle Model")
  public String getVehicleModel() {
    return vehicleModel;
  }

  public void setVehicleModel(String vehicleModel) {
    this.vehicleModel = vehicleModel;
  }

  public UpdateDeviceModel licensePlate(String licensePlate) {
    this.licensePlate = licensePlate;
    return this;
  }

   /**
   * Vehicle Plate
   * @return licensePlate
  **/
  @ApiModelProperty(value = "Vehicle Plate")
  public String getLicensePlate() {
    return licensePlate;
  }

  public void setLicensePlate(String licensePlate) {
    this.licensePlate = licensePlate;
  }

  public UpdateDeviceModel licenseExpiration(Long licenseExpiration) {
    this.licenseExpiration = licenseExpiration;
    return this;
  }

   /**
   * License Expiration UTC
   * @return licenseExpiration
  **/
  @ApiModelProperty(example = "1514707261000", value = "License Expiration UTC")
  public Long getLicenseExpiration() {
    return licenseExpiration;
  }

  public void setLicenseExpiration(Long licenseExpiration) {
    this.licenseExpiration = licenseExpiration;
  }

  public UpdateDeviceModel reminderInterval(String reminderInterval) {
    this.reminderInterval = reminderInterval;
    return this;
  }

   /**
   * Reminder Interval
   * @return reminderInterval
  **/
  @ApiModelProperty(value = "Reminder Interval")
  public String getReminderInterval() {
    return reminderInterval;
  }

  public void setReminderInterval(String reminderInterval) {
    this.reminderInterval = reminderInterval;
  }

  public UpdateDeviceModel reminderMessage(String reminderMessage) {
    this.reminderMessage = reminderMessage;
    return this;
  }

   /**
   * Reminder Message
   * @return reminderMessage
  **/
  @ApiModelProperty(value = "Reminder Message")
  public String getReminderMessage() {
    return reminderMessage;
  }

  public void setReminderMessage(String reminderMessage) {
    this.reminderMessage = reminderMessage;
  }

  public UpdateDeviceModel maintenanceNotes(String maintenanceNotes) {
    this.maintenanceNotes = maintenanceNotes;
    return this;
  }

   /**
   * Maintenance Notes
   * @return maintenanceNotes
  **/
  @ApiModelProperty(value = "Maintenance Notes")
  public String getMaintenanceNotes() {
    return maintenanceNotes;
  }

  public void setMaintenanceNotes(String maintenanceNotes) {
    this.maintenanceNotes = maintenanceNotes;
  }

  public UpdateDeviceModel maintenanceInterval1(Double maintenanceInterval1) {
    this.maintenanceInterval1 = maintenanceInterval1;
    return this;
  }

   /**
   * Maintenance Interval1
   * @return maintenanceInterval1
  **/
  @ApiModelProperty(value = "Maintenance Interval1")
  public Double getMaintenanceInterval1() {
    return maintenanceInterval1;
  }

  public void setMaintenanceInterval1(Double maintenanceInterval1) {
    this.maintenanceInterval1 = maintenanceInterval1;
  }

  public UpdateDeviceModel lastMaintenance1(Double lastMaintenance1) {
    this.lastMaintenance1 = lastMaintenance1;
    return this;
  }

   /**
   * Last Maintenance 1
   * @return lastMaintenance1
  **/
  @ApiModelProperty(value = "Last Maintenance 1")
  public Double getLastMaintenance1() {
    return lastMaintenance1;
  }

  public void setLastMaintenance1(Double lastMaintenance1) {
    this.lastMaintenance1 = lastMaintenance1;
  }

  public UpdateDeviceModel maintenanceInterval2(Double maintenanceInterval2) {
    this.maintenanceInterval2 = maintenanceInterval2;
    return this;
  }

   /**
   * Maintenance Interval2
   * @return maintenanceInterval2
  **/
  @ApiModelProperty(value = "Maintenance Interval2")
  public Double getMaintenanceInterval2() {
    return maintenanceInterval2;
  }

  public void setMaintenanceInterval2(Double maintenanceInterval2) {
    this.maintenanceInterval2 = maintenanceInterval2;
  }

  public UpdateDeviceModel notifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
    return this;
  }

   /**
   * Notification EMail Address
   * @return notifyEmail
  **/
  @ApiModelProperty(value = "Notification EMail Address")
  public String getNotifyEmail() {
    return notifyEmail;
  }

  public void setNotifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
  }

  public UpdateDeviceModel faultCodes(String faultCodes) {
    this.faultCodes = faultCodes;
    return this;
  }

   /**
   * Last Fault Code
   * @return faultCodes
  **/
  @ApiModelProperty(value = "Last Fault Code")
  public String getFaultCodes() {
    return faultCodes;
  }

  public void setFaultCodes(String faultCodes) {
    this.faultCodes = faultCodes;
  }

  public UpdateDeviceModel equipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
    return this;
  }

   /**
   * Equipment Type
   * @return equipmentType
  **/
  @ApiModelProperty(value = "Equipment Type")
  public String getEquipmentType() {
    return equipmentType;
  }

  public void setEquipmentType(String equipmentType) {
    this.equipmentType = equipmentType;
  }

  public UpdateDeviceModel nextServiceTime(Long nextServiceTime) {
    this.nextServiceTime = nextServiceTime;
    return this;
  }

   /**
   * Next Service Time UTC
   * @return nextServiceTime
  **/
  @ApiModelProperty(example = "1514707261000", value = "Next Service Time UTC")
  public Long getNextServiceTime() {
    return nextServiceTime;
  }

  public void setNextServiceTime(Long nextServiceTime) {
    this.nextServiceTime = nextServiceTime;
  }

  public UpdateDeviceModel maximumSpeed(Double maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
    return this;
  }

   /**
   * Maximum speed
   * @return maximumSpeed
  **/
  @ApiModelProperty(value = "Maximum speed")
  public Double getMaximumSpeed() {
    return maximumSpeed;
  }

  public void setMaximumSpeed(Double maximumSpeed) {
    this.maximumSpeed = maximumSpeed;
  }

  public UpdateDeviceModel notifyEnable(Boolean notifyEnable) {
    this.notifyEnable = notifyEnable;
    return this;
  }

   /**
   * Notification enabled?
   * @return notifyEnable
  **/
  @ApiModelProperty(value = "Notification enabled?")
  public Boolean isNotifyEnable() {
    return notifyEnable;
  }

  public void setNotifyEnable(Boolean notifyEnable) {
    this.notifyEnable = notifyEnable;
  }

  public UpdateDeviceModel reportedOdometer(Double reportedOdometer) {
    this.reportedOdometer = reportedOdometer;
    return this;
  }

   /**
   * Reported odometr
   * @return reportedOdometer
  **/
  @ApiModelProperty(value = "Reported odometr")
  public Double getReportedOdometer() {
    return reportedOdometer;
  }

  public void setReportedOdometer(Double reportedOdometer) {
    this.reportedOdometer = reportedOdometer;
  }

  public UpdateDeviceModel reportedEngineHours(Double reportedEngineHours) {
    this.reportedEngineHours = reportedEngineHours;
    return this;
  }

   /**
   * Reported Engine Hours
   * @return reportedEngineHours
  **/
  @ApiModelProperty(value = "Reported Engine Hours")
  public Double getReportedEngineHours() {
    return reportedEngineHours;
  }

  public void setReportedEngineHours(Double reportedEngineHours) {
    this.reportedEngineHours = reportedEngineHours;
  }

  public UpdateDeviceModel lastEngHoursMaint(Double lastEngHoursMaint) {
    this.lastEngHoursMaint = lastEngHoursMaint;
    return this;
  }

   /**
   * Last Engine Hours Maintenance
   * @return lastEngHoursMaint
  **/
  @ApiModelProperty(value = "Last Engine Hours Maintenance")
  public Double getLastEngHoursMaint() {
    return lastEngHoursMaint;
  }

  public void setLastEngHoursMaint(Double lastEngHoursMaint) {
    this.lastEngHoursMaint = lastEngHoursMaint;
  }

  public UpdateDeviceModel engHoursMaintInterval(Double engHoursMaintInterval) {
    this.engHoursMaintInterval = engHoursMaintInterval;
    return this;
  }

   /**
   * Last Engine Hours Maintenance Interval
   * @return engHoursMaintInterval
  **/
  @ApiModelProperty(value = "Last Engine Hours Maintenance Interval")
  public Double getEngHoursMaintInterval() {
    return engHoursMaintInterval;
  }

  public void setEngHoursMaintInterval(Double engHoursMaintInterval) {
    this.engHoursMaintInterval = engHoursMaintInterval;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeviceModel updateDeviceModel = (UpdateDeviceModel) o;
    return Objects.equals(this.deviceId, updateDeviceModel.deviceId) &&
        Objects.equals(this.description, updateDeviceModel.description) &&
        Objects.equals(this.shortName, updateDeviceModel.shortName) &&
        Objects.equals(this.vehicleId, updateDeviceModel.vehicleId) &&
        Objects.equals(this.vehicleMake, updateDeviceModel.vehicleMake) &&
        Objects.equals(this.vehicleModel, updateDeviceModel.vehicleModel) &&
        Objects.equals(this.licensePlate, updateDeviceModel.licensePlate) &&
        Objects.equals(this.licenseExpiration, updateDeviceModel.licenseExpiration) &&
        Objects.equals(this.reminderInterval, updateDeviceModel.reminderInterval) &&
        Objects.equals(this.reminderMessage, updateDeviceModel.reminderMessage) &&
        Objects.equals(this.maintenanceNotes, updateDeviceModel.maintenanceNotes) &&
        Objects.equals(this.maintenanceInterval1, updateDeviceModel.maintenanceInterval1) &&
        Objects.equals(this.lastMaintenance1, updateDeviceModel.lastMaintenance1) &&
        Objects.equals(this.maintenanceInterval2, updateDeviceModel.maintenanceInterval2) &&
        Objects.equals(this.notifyEmail, updateDeviceModel.notifyEmail) &&
        Objects.equals(this.faultCodes, updateDeviceModel.faultCodes) &&
        Objects.equals(this.equipmentType, updateDeviceModel.equipmentType) &&
        Objects.equals(this.nextServiceTime, updateDeviceModel.nextServiceTime) &&
        Objects.equals(this.maximumSpeed, updateDeviceModel.maximumSpeed) &&
        Objects.equals(this.notifyEnable, updateDeviceModel.notifyEnable) &&
        Objects.equals(this.reportedOdometer, updateDeviceModel.reportedOdometer) &&
        Objects.equals(this.reportedEngineHours, updateDeviceModel.reportedEngineHours) &&
        Objects.equals(this.lastEngHoursMaint, updateDeviceModel.lastEngHoursMaint) &&
        Objects.equals(this.engHoursMaintInterval, updateDeviceModel.engHoursMaintInterval);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, description, shortName, vehicleId, vehicleMake, vehicleModel, licensePlate, licenseExpiration, reminderInterval, reminderMessage, maintenanceNotes, maintenanceInterval1, lastMaintenance1, maintenanceInterval2, notifyEmail, faultCodes, equipmentType, nextServiceTime, maximumSpeed, notifyEnable, reportedOdometer, reportedEngineHours, lastEngHoursMaint, engHoursMaintInterval);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeviceModel {\n");
    
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    vehicleId: ").append(toIndentedString(vehicleId)).append("\n");
    sb.append("    vehicleMake: ").append(toIndentedString(vehicleMake)).append("\n");
    sb.append("    vehicleModel: ").append(toIndentedString(vehicleModel)).append("\n");
    sb.append("    licensePlate: ").append(toIndentedString(licensePlate)).append("\n");
    sb.append("    licenseExpiration: ").append(toIndentedString(licenseExpiration)).append("\n");
    sb.append("    reminderInterval: ").append(toIndentedString(reminderInterval)).append("\n");
    sb.append("    reminderMessage: ").append(toIndentedString(reminderMessage)).append("\n");
    sb.append("    maintenanceNotes: ").append(toIndentedString(maintenanceNotes)).append("\n");
    sb.append("    maintenanceInterval1: ").append(toIndentedString(maintenanceInterval1)).append("\n");
    sb.append("    lastMaintenance1: ").append(toIndentedString(lastMaintenance1)).append("\n");
    sb.append("    maintenanceInterval2: ").append(toIndentedString(maintenanceInterval2)).append("\n");
    sb.append("    notifyEmail: ").append(toIndentedString(notifyEmail)).append("\n");
    sb.append("    faultCodes: ").append(toIndentedString(faultCodes)).append("\n");
    sb.append("    equipmentType: ").append(toIndentedString(equipmentType)).append("\n");
    sb.append("    nextServiceTime: ").append(toIndentedString(nextServiceTime)).append("\n");
    sb.append("    maximumSpeed: ").append(toIndentedString(maximumSpeed)).append("\n");
    sb.append("    notifyEnable: ").append(toIndentedString(notifyEnable)).append("\n");
    sb.append("    reportedOdometer: ").append(toIndentedString(reportedOdometer)).append("\n");
    sb.append("    reportedEngineHours: ").append(toIndentedString(reportedEngineHours)).append("\n");
    sb.append("    lastEngHoursMaint: ").append(toIndentedString(lastEngHoursMaint)).append("\n");
    sb.append("    engHoursMaintInterval: ").append(toIndentedString(engHoursMaintInterval)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

