/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UserCreateModel
 */

public class UserCreateModel {
  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("contactName")
  private String contactName = null;

  @SerializedName("contactPhone")
  private String contactPhone = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("fistLoginPage")
  private String fistLoginPage = null;

  @SerializedName("lastLogin")
  private Long lastLogin = null;

  @SerializedName("loginEmail")
  private String loginEmail = null;

  @SerializedName("notifyEmail")
  private String notifyEmail = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("preferredVehicleId")
  private String preferredVehicleId = null;

  @SerializedName("roleId")
  private String roleId = null;

  @SerializedName("timeZone")
  private String timeZone = null;

  @SerializedName("userId")
  private String userId = null;

  public UserCreateModel active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(value = "")
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public UserCreateModel contactName(String contactName) {
    this.contactName = contactName;
    return this;
  }

   /**
   * Get contactName
   * @return contactName
  **/
  @ApiModelProperty(value = "")
  public String getContactName() {
    return contactName;
  }

  public void setContactName(String contactName) {
    this.contactName = contactName;
  }

  public UserCreateModel contactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
    return this;
  }

   /**
   * Get contactPhone
   * @return contactPhone
  **/
  @ApiModelProperty(value = "")
  public String getContactPhone() {
    return contactPhone;
  }

  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  public UserCreateModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UserCreateModel fistLoginPage(String fistLoginPage) {
    this.fistLoginPage = fistLoginPage;
    return this;
  }

   /**
   * Get fistLoginPage
   * @return fistLoginPage
  **/
  @ApiModelProperty(value = "")
  public String getFistLoginPage() {
    return fistLoginPage;
  }

  public void setFistLoginPage(String fistLoginPage) {
    this.fistLoginPage = fistLoginPage;
  }

  public UserCreateModel lastLogin(Long lastLogin) {
    this.lastLogin = lastLogin;
    return this;
  }

   /**
   * Get lastLogin
   * @return lastLogin
  **/
  @ApiModelProperty(value = "")
  public Long getLastLogin() {
    return lastLogin;
  }

  public void setLastLogin(Long lastLogin) {
    this.lastLogin = lastLogin;
  }

  public UserCreateModel loginEmail(String loginEmail) {
    this.loginEmail = loginEmail;
    return this;
  }

   /**
   * Get loginEmail
   * @return loginEmail
  **/
  @ApiModelProperty(value = "")
  public String getLoginEmail() {
    return loginEmail;
  }

  public void setLoginEmail(String loginEmail) {
    this.loginEmail = loginEmail;
  }

  public UserCreateModel notifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
    return this;
  }

   /**
   * Get notifyEmail
   * @return notifyEmail
  **/
  @ApiModelProperty(value = "")
  public String getNotifyEmail() {
    return notifyEmail;
  }

  public void setNotifyEmail(String notifyEmail) {
    this.notifyEmail = notifyEmail;
  }

  public UserCreateModel password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UserCreateModel preferredVehicleId(String preferredVehicleId) {
    this.preferredVehicleId = preferredVehicleId;
    return this;
  }

   /**
   * Get preferredVehicleId
   * @return preferredVehicleId
  **/
  @ApiModelProperty(value = "")
  public String getPreferredVehicleId() {
    return preferredVehicleId;
  }

  public void setPreferredVehicleId(String preferredVehicleId) {
    this.preferredVehicleId = preferredVehicleId;
  }

  public UserCreateModel roleId(String roleId) {
    this.roleId = roleId;
    return this;
  }

   /**
   * Get roleId
   * @return roleId
  **/
  @ApiModelProperty(value = "")
  public String getRoleId() {
    return roleId;
  }

  public void setRoleId(String roleId) {
    this.roleId = roleId;
  }

  public UserCreateModel timeZone(String timeZone) {
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @ApiModelProperty(value = "")
  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public UserCreateModel userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserCreateModel userCreateModel = (UserCreateModel) o;
    return Objects.equals(this.active, userCreateModel.active) &&
        Objects.equals(this.contactName, userCreateModel.contactName) &&
        Objects.equals(this.contactPhone, userCreateModel.contactPhone) &&
        Objects.equals(this.description, userCreateModel.description) &&
        Objects.equals(this.fistLoginPage, userCreateModel.fistLoginPage) &&
        Objects.equals(this.lastLogin, userCreateModel.lastLogin) &&
        Objects.equals(this.loginEmail, userCreateModel.loginEmail) &&
        Objects.equals(this.notifyEmail, userCreateModel.notifyEmail) &&
        Objects.equals(this.password, userCreateModel.password) &&
        Objects.equals(this.preferredVehicleId, userCreateModel.preferredVehicleId) &&
        Objects.equals(this.roleId, userCreateModel.roleId) &&
        Objects.equals(this.timeZone, userCreateModel.timeZone) &&
        Objects.equals(this.userId, userCreateModel.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(active, contactName, contactPhone, description, fistLoginPage, lastLogin, loginEmail, notifyEmail, password, preferredVehicleId, roleId, timeZone, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserCreateModel {\n");
    
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    contactName: ").append(toIndentedString(contactName)).append("\n");
    sb.append("    contactPhone: ").append(toIndentedString(contactPhone)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fistLoginPage: ").append(toIndentedString(fistLoginPage)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("    loginEmail: ").append(toIndentedString(loginEmail)).append("\n");
    sb.append("    notifyEmail: ").append(toIndentedString(notifyEmail)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    preferredVehicleId: ").append(toIndentedString(preferredVehicleId)).append("\n");
    sb.append("    roleId: ").append(toIndentedString(roleId)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

