/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints;

import com.endpoints.clients.DevicesApi;
import com.endpoints.models.UpdateDeviceModel;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.endpoints.GsonObjectMapper.gson;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;

/**
 * API tests for DevicesApi
 */
@Ignore
public class DevicesApiTest {

    private DevicesApi api;

    @BeforeClass
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("https://api.staging.clearpathgps.com/v3.0"))).devices();
    }

    /**
     * OK
     */
    @Test
    public void shouldSee200AfterFindAllDevicesForAccountIdUsingGET() {
        Boolean includeInactive = null;
        api.findAllDevicesForAccountIdUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterFindAllDevicesForAccountIdUsingGET() {
        Boolean includeInactive = null;
        api.findAllDevicesForAccountIdUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterFindAllDevicesForAccountIdUsingGET() {
        Boolean includeInactive = null;
        api.findAllDevicesForAccountIdUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterFindAllDevicesForGroupIdUsingGET() {
        String groupId = null;
        Boolean includeInactive = null;
        api.findAllDevicesForGroupIdUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterFindAllDevicesForGroupIdUsingGET() {
        String groupId = null;
        Boolean includeInactive = null;
        api.findAllDevicesForGroupIdUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterFindAllDevicesForGroupIdUsingGET() {
        String groupId = null;
        Boolean includeInactive = null;
        api.findAllDevicesForGroupIdUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterFindAllGroupsForDeviceIdUsingGET() {
        String deviceId = null;
        api.findAllGroupsForDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterFindAllGroupsForDeviceIdUsingGET() {
        String deviceId = null;
        api.findAllGroupsForDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterFindAllGroupsForDeviceIdUsingGET() {
        String deviceId = null;
        api.findAllGroupsForDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetDeviceByDeviceIdUsingGET() {
        String deviceId = null;
        api.getDeviceByDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetDeviceByDeviceIdUsingGET() {
        String deviceId = null;
        api.getDeviceByDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Access denied
     */
    @Test
    public void shouldSee403AfterGetDeviceByDeviceIdUsingGET() {
        String deviceId = null;
        api.getDeviceByDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Device not found
     */
    @Test
    public void shouldSee404AfterGetDeviceByDeviceIdUsingGET() {
        String deviceId = null;
        api.getDeviceByDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetDeviceByDeviceIdUsingGET() {
        String deviceId = null;
        api.getDeviceByDeviceIdUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Invalid JSON
     */
    @Test
    public void shouldSee400AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Insufficient privileges
     */
    @Test
    public void shouldSee403AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Device not found
     */
    @Test
    public void shouldSee404AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterUpdateDeviceUsingPUT() {
        UpdateDeviceModel deviceModel = null;
        api.updateDeviceUsingPUT()
                .body(deviceModel).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}