/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints;


import com.endpoints.clients.EventsApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.endpoints.GsonObjectMapper.gson;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;

/**
 * API tests for EventsApi
 */
@Ignore
public class EventsApiTest {

    private EventsApi api;

    @BeforeClass
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("https://api.staging.clearpathgps.com/v3.0"))).events();
    }

    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetDeviceEventsUsingGET() {
        String deviceId = null;
        Long from = null;
        Long to = null;
        Integer limit = null;
        String limitType = null;
        api.getDeviceEventsUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetDeviceEventsUsingGET() {
        String deviceId = null;
        Long from = null;
        Long to = null;
        Integer limit = null;
        String limitType = null;
        api.getDeviceEventsUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Access denied
     */
    @Test
    public void shouldSee403AfterGetDeviceEventsUsingGET() {
        String deviceId = null;
        Long from = null;
        Long to = null;
        Integer limit = null;
        String limitType = null;
        api.getDeviceEventsUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Device not found
     */
    @Test
    public void shouldSee404AfterGetDeviceEventsUsingGET() {
        String deviceId = null;
        Long from = null;
        Long to = null;
        Integer limit = null;
        String limitType = null;
        api.getDeviceEventsUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetDeviceEventsUsingGET() {
        String deviceId = null;
        Long from = null;
        Long to = null;
        Integer limit = null;
        String limitType = null;
        api.getDeviceEventsUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetLastDeviceEventUsingGET() {
        String deviceId = null;
        Long to = null;
        api.getLastDeviceEventUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetLastDeviceEventUsingGET() {
        String deviceId = null;
        Long to = null;
        api.getLastDeviceEventUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Access denied
     */
    @Test
    public void shouldSee403AfterGetLastDeviceEventUsingGET() {
        String deviceId = null;
        Long to = null;
        api.getLastDeviceEventUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Device not found
     */
    @Test
    public void shouldSee404AfterGetLastDeviceEventUsingGET() {
        String deviceId = null;
        Long to = null;
        api.getLastDeviceEventUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetLastDeviceEventUsingGET() {
        String deviceId = null;
        Long to = null;
        api.getLastDeviceEventUsingGET()
                .deviceIdPath(deviceId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetLastFleetEventsUsingGET() {
        Long to = null;
        Boolean includeInactive = null;
        api.getLastFleetEventsUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetLastFleetEventsUsingGET() {
        Long to = null;
        Boolean includeInactive = null;
        api.getLastFleetEventsUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetLastFleetEventsUsingGET() {
        Long to = null;
        Boolean includeInactive = null;
        api.getLastFleetEventsUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetLastGroupEventsUsingGET() {
        String groupId = null;
        Long to = null;
        Boolean includeInactive = null;
        api.getLastGroupEventsUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetLastGroupEventsUsingGET() {
        String groupId = null;
        Long to = null;
        Boolean includeInactive = null;
        api.getLastGroupEventsUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetLastGroupEventsUsingGET() {
        String groupId = null;
        Long to = null;
        Boolean includeInactive = null;
        api.getLastGroupEventsUsingGET()
                .groupIdPath(groupId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}