/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints;


import com.endpoints.clients.ReportsApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.endpoints.GsonObjectMapper.gson;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;

/**
 * API tests for ReportsApi
 */
@Ignore
public class ReportsApiTest {

    private ReportsApi api;

    @BeforeClass
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("https://api.staging.clearpathgps.com/v3.0"))).reports();
    }

    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetReportsDescriptionUsingGET() {
        api.getReportsDescriptionUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetReportsDescriptionUsingGET() {
        api.getReportsDescriptionUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetReportsDescriptionUsingGET() {
        api.getReportsDescriptionUsingGET().execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterGetReportsUsingGET() {
        String reportGroup = null;
        String reportId = null;
        Long from = null;
        Long to = null;
        String deviceId = null;
        String groupId = null;
        String option = null;
        api.getReportsUsingGET()
                .reportGroupQuery(reportGroup)
                .reportIdQuery(reportId)
                .fromQuery(from)
                .toQuery(to).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterGetReportsUsingGET() {
        String reportGroup = null;
        String reportId = null;
        Long from = null;
        Long to = null;
        String deviceId = null;
        String groupId = null;
        String option = null;
        api.getReportsUsingGET()
                .reportGroupQuery(reportGroup)
                .reportIdQuery(reportId)
                .fromQuery(from)
                .toQuery(to).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterGetReportsUsingGET() {
        String reportGroup = null;
        String reportId = null;
        Long from = null;
        Long to = null;
        String deviceId = null;
        String groupId = null;
        String option = null;
        api.getReportsUsingGET()
                .reportGroupQuery(reportGroup)
                .reportIdQuery(reportId)
                .fromQuery(from)
                .toQuery(to).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}