/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints;


import com.endpoints.clients.SearchApi;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.filter.log.ErrorLoggingFilter;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Ignore;
import org.testng.annotations.Test;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static com.endpoints.GsonObjectMapper.gson;
import static io.restassured.config.ObjectMapperConfig.objectMapperConfig;
import static io.restassured.config.RestAssuredConfig.config;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private SearchApi api;

    @BeforeClass
    public void createApi() {
        api = ApiClient.api(ApiClient.Config.apiConfig().reqSpecSupplier(
                () -> new RequestSpecBuilder().setConfig(config().objectMapperConfig(objectMapperConfig().defaultObjectMapper(gson())))
                        .addFilter(new ErrorLoggingFilter())
                        .setBaseUri("https://api.staging.clearpathgps.com/v3.0"))).search();
    }

    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchDevicesForDriverUsingGET() {
        String driverId = null;
        api.searchDevicesForDriverUsingGET()
                .driverIdPath(driverId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchDevicesForDriverUsingGET() {
        String driverId = null;
        api.searchDevicesForDriverUsingGET()
                .driverIdPath(driverId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchDevicesForDriverUsingGET() {
        String driverId = null;
        api.searchDevicesForDriverUsingGET()
                .driverIdPath(driverId).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchDevicesUsingGET() {
        String search = null;
        api.searchDevicesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchDevicesUsingGET() {
        String search = null;
        api.searchDevicesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchDevicesUsingGET() {
        String search = null;
        api.searchDevicesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchDriversUsingGET() {
        String search = null;
        api.searchDriversUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchDriversUsingGET() {
        String search = null;
        api.searchDriversUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchDriversUsingGET() {
        String search = null;
        api.searchDriversUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchGeozonesUsingGET() {
        String search = null;
        api.searchGeozonesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchGeozonesUsingGET() {
        String search = null;
        api.searchGeozonesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchGeozonesUsingGET() {
        String search = null;
        api.searchGeozonesUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchGroupsUsingGET() {
        String search = null;
        api.searchGroupsUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchGroupsUsingGET() {
        String search = null;
        api.searchGroupsUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchGroupsUsingGET() {
        String search = null;
        api.searchGroupsUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }


    /**
     * OK
     */
    @Test
    public void shouldSee200AfterSearchUsingGET() {
        String search = null;
        api.searchUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Unauthorized
     */
    @Test
    public void shouldSee401AfterSearchUsingGET() {
        String search = null;
        api.searchUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

    /**
     * Too many requests
     */
    @Test
    public void shouldSee429AfterSearchUsingGET() {
        String search = null;
        api.searchUsingGET()
                .searchQuery(search).execute(r -> r.prettyPeek());
        // TODO: test validations
    }

}