/*
 * API V3
 * Please log in using your email and password in order to use API
 *
 * OpenAPI spec version: 3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.endpoints.clients;

import com.endpoints.models.PasswordRecoveryModel;
import com.google.gson.reflect.TypeToken;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.builder.ResponseSpecBuilder;
import io.restassured.response.Response;

import java.lang.reflect.Type;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.function.Supplier;

import static io.restassured.http.Method.*;

public class PasswordRecoveryApi {

    private RequestSpecBuilder reqSpec;

    private PasswordRecoveryApi(RequestSpecBuilder reqSpec) {
        this.reqSpec = reqSpec;
    }

    public static PasswordRecoveryApi passwordRecovery(RequestSpecBuilder reqSpec) {
        return new PasswordRecoveryApi(reqSpec);
    }


    public ResetPasswordUsingPOSTOper resetPasswordUsingPOST() {
        return new ResetPasswordUsingPOSTOper(reqSpec);
    }

    /**
    * Customise request specification
    */
    public PasswordRecoveryApi reqSpec(Consumer<RequestSpecBuilder> consumer) {
        consumer.accept(reqSpec);
        return this;
    }

    /**
     * Password recovery
     * 
     *
     * @see #body passwordRecoveryModel (required)
     * return String
     */
    public class ResetPasswordUsingPOSTOper {

        public static final String REQ_URI = "/password-recovery";

        private RequestSpecBuilder reqSpec;

        private ResponseSpecBuilder respSpec;

        public ResetPasswordUsingPOSTOper() {
            this.reqSpec = new RequestSpecBuilder();
            reqSpec.setContentType("application/json");
            reqSpec.setAccept("*/*");
            this.respSpec = new ResponseSpecBuilder();
        }

        public ResetPasswordUsingPOSTOper(RequestSpecBuilder reqSpec) {
            this.reqSpec = reqSpec;
            reqSpec.setContentType("application/json");
            reqSpec.setAccept("*/*");
            this.respSpec = new ResponseSpecBuilder();
        }

        /**
         * POST /password-recovery
         */
        public <T> T execute(Function<Response, T> handler) {
            return handler.apply(RestAssured.given().spec(reqSpec.build()).expect().spec(respSpec.build()).when().request(POST, REQ_URI));
        }

        /**
         * POST /password-recovery
         * @return String
         */
        public String executeAs(Function<Response, Response> handler) {
            Type type = new TypeToken<String>(){}.getType();
            return execute(handler).as(type);
        }

         /**
         * @param passwordRecoveryModel (PasswordRecoveryModel) passwordRecoveryModel (required)
         */
        public ResetPasswordUsingPOSTOper body(PasswordRecoveryModel passwordRecoveryModel) {
            reqSpec.setBody(passwordRecoveryModel);
            return this;
        }

        /**
         * Customise request specification
         */
        public ResetPasswordUsingPOSTOper reqSpec(Consumer<RequestSpecBuilder> consumer) {
            consumer.accept(reqSpec);
            return this;
        }

        /**
         * Customise response specification
         */
        public ResetPasswordUsingPOSTOper respSpec(Consumer<ResponseSpecBuilder> consumer) {
            consumer.accept(respSpec);
            return this;
        }
    }
}